"""Migration description

Revision ID: 6a261ea6cdde
Revises: 
Create Date: 2023-08-10 10:11:05.931864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a261ea6cdde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data1', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('data',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.String(length=10000),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('data1')

    # ### end Alembic commands ###
